CREATE TABLE USERS(
USER_ID INT NOT NULL PRIMARY KEY IDENTITY,
USERNAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL);

INSERT INTO USERS VALUES
('Noel','emailnoel@hotmail.com','1234567');

SELECT * FROM USERS WHERE EMAIL = 'emailnoel@hotmail.com' AND PASSWORD = '1234567';

DROP TABLE USERS